### ISSUE TITLE
please improve formatting quality

### ISSUE THREAD

**Issue by milankowww** [NCSC-NL/log4shell#497] opened 2021-12-16 12:58 UTC
The quality of markdown tables is slowly deteriorating:
- some entries don't have a trailing `|`, some do
- some table uses a different separator than `|:----`, namely `|----`

This makes it hard for automated parsing tools to access the data.

Doing a one-shot cleanup and sending a pull request fixing half the entries would not be wise, because it would make all the other waiting pull requests unmergeable. Also, implementing a commit hook would make the entire file un-commitable.

My idea would be to
- fix `|:---` manually
- ask contributors for a more rigid input formatting
- add a pre-merge-commit hook, that would only check the diff for violations of the code, so that the old code can still be ugly (for some time)

**Comment by maertsen** [comment] 2021-12-16 13:03
We would appreciate PR's for all of your suggestions, @milankowww.

**Comment by RobinFlikkema** [comment] 2021-12-17 12:33
This has been fixed since commit d9528bd

**Comment by tschmidtb51** [comment] 2021-12-23 18:55
@milankowww We added a GH Action to check the table for new PRs.

**Comment by edwinschaap** [comment] 2021-12-27 09:35
Closing this since the issue is fixed and a GH Action is in place.
👍 Thanks @RobinFlikkema, @tschmidtb51 and @milankowww!

**Closed by edwinschaap** 2021-12-27 09:35 UTC
Labels: software, PR-requested
